//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmverwaltung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public Film()
        {
            this.FilmSchauspieler = new HashSet<FilmSchauspieler>();
        }
    
        public int ID_Film { get; set; }
        public string Name { get; set; }
        public string Genre { get; set; }
        public Nullable<int> Laenge { get; set; }
        public int ProduzentId { get; set; }
    
        public virtual Produzent Produzent { get; set; }
        public virtual ICollection<FilmSchauspieler> FilmSchauspieler { get; set; }
    }
}
