//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmverwaltung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produzent
    {
        public Produzent()
        {
            this.Film = new HashSet<Film>();
            this.Serie = new HashSet<Serie>();
        }
    
        public int ID_Produzent { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string Firma { get; set; }
    
        public virtual ICollection<Film> Film { get; set; }
        public virtual ICollection<Serie> Serie { get; set; }
    }
}
