//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmverwaltung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schauspieler
    {
        public Schauspieler()
        {
            this.FilmSchauspieler = new HashSet<FilmSchauspieler>();
            this.SerieSchauspieler = new HashSet<SerieSchauspieler>();
        }
    
        public int ID_Schauspieler { get; set; }
        public string Vorname { get; set; }
        public string Name { get; set; }
        public string VermittlungsAgentur { get; set; }
    
        public virtual ICollection<FilmSchauspieler> FilmSchauspieler { get; set; }
        public virtual ICollection<SerieSchauspieler> SerieSchauspieler { get; set; }
    }
}
